name: Deploy
on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.x"

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "musicale"
          root: "./dist"
          entrypoint: "./server.ts"
