name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            any activity in the past 30 days. It will be closed if no further activity
            occurs. Thank you for your contributions.
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has not had
            any activity in the past 30 days. It will be closed if no further activity
            occurs. Thank you for your contributions.
          days-before-stale: 30
          days-before-close: 7
          exempt-issue-labels: pinned
          exempt-pr-labels: pinned
          stale-issue-label: wontfix
